services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3031:3031"
    environment:
      PORT: "3031"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - api
